fix(bin): print err msg to stderr in `ex`

diff --git a/.bin/ex b/.bin/ex
--- a/.bin/ex
+++ b/.bin/ex
@@ -5,7 +5,7 @@
 # Check if a file/directory does not exist
 checkne() {
     if [ -e "$1" ]; then
-        echo "Error: '$1' already exists"
+        echo "Error: '$1' already exists" >&2
         return 1
     fi
     return 0
@@ -81,7 +81,7 @@ main() {
     fname=$1
 
     if [ ! -f "$fname" ]; then
-        echo "'$fname' is not a valid file"
+        echo "'$fname' is not a valid file" >&2
         return 1
     fi
 
@@ -236,7 +236,7 @@ main() {
         7z x "$fname" -o"$froot"
         ;;
     *)
-        echo "'$fname' cannot be extracted"
+        echo "'$fname' cannot be extracted" >&2
         ;;
     esac
 
