refactor(bin): ex: cleanup naming and comments

diff --git a/.bin/ex b/.bin/ex
--- a/.bin/ex
+++ b/.bin/ex
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
 # vim: ft=sh ts=4 sw=4 sts=4 et :
+# Extract files from archive, wisely
 
-# Function to check if directory exists
-checkdir() {
+# Check if a file/directory does not exist
+checkne() {
     if [[ -e "$1" ]]; then
         echo "Error: '$1' already exists"
         return 1
@@ -10,9 +11,7 @@ checkdir() {
     return 0
 }
 
-# ex - archive extractor
-# usage: ex <file>
-ex() {
+main() {
     if [[ ! -f "$1" ]]; then
         echo "'$1' is not a valid file"
         return 1
@@ -30,7 +29,7 @@ ex() {
     case "$1" in
     *.tar.Z)
         if (($(tar tZf "$1" | wc -l) > 1)); then
-            checkdir "$frootname" && mkdir "$frootname" &&
+            checkne "$frootname" && mkdir "$frootname" &&
                 tar xZf "$1" -C "$frootname" || return 1
         else
             tar xZf "$1"
@@ -39,7 +38,7 @@ ex() {
     *.Z) uncompress "$1" ;;
     *.tar.bz2 | *.tbz2)
         if (($(tar tjf "$1" | wc -l) > 1)); then
-            checkdir "$frootname" && mkdir "$frootname" &&
+            checkne "$frootname" && mkdir "$frootname" &&
                 tar xjf "$1" -C "$frootname" || return 1
         else
             tar xjf "$1"
@@ -48,16 +47,16 @@ ex() {
     *.bz2) bunzip2 "$1" ;;
     *.tar.gz | *.tgz)
         if (($(tar tzf "$1" | wc -l) > 1)); then
-            checkdir "$frootname" && mkdir "$frootname" &&
+            checkne "$frootname" && mkdir "$frootname" &&
                 tar xzf "$1" -C "$frootname" || return 1
         else
             tar xzf "$1"
         fi
         ;;
-    *.gz) gunzip -c "$1" >"$frootname" ;;
+    *.gz) checkne "$frootname" && gunzip -c "$1" >"$frootname" || return 1 ;;
     *.tar.xz | *.txz)
         if (($(tar tJf "$1" | wc -l) > 1)); then
-            checkdir "$frootname" && mkdir "$frootname" &&
+            checkne "$frootname" && mkdir "$frootname" &&
                 tar xJf "$1" -C "$frootname" || return 1
         else
             tar xJf "$1"
@@ -66,7 +65,7 @@ ex() {
     *.xz) unxz "$1" ;;
     *.tar.lzma)
         if (($(tar --lzma -tf "$1" | wc -l) > 1)); then
-            checkdir "$frootname" && mkdir "$frootname" &&
+            checkne "$frootname" && mkdir "$frootname" &&
                 tar --lzma -xf "$1" -C "$frootname" || return 1
         else
             tar --lzma -xf "$1"
@@ -75,7 +74,7 @@ ex() {
     *.lzma) unlzma "$1" ;;
     *.tar.zst | *.tzst)
         if (($(tar --zstd -tf "$1" | wc -l) > 1)); then
-            checkdir "$frootname" && mkdir "$frootname" &&
+            checkne "$frootname" && mkdir "$frootname" &&
                 tar --zstd -xf "$1" -C "$frootname" || return 1
         else
             tar --zstd -xf "$1"
@@ -84,7 +83,7 @@ ex() {
     *.zst) zstd -d "$1" ;;
     *.tar.lz4)
         if (($(tar --use-compress-program=lz4 -tf "$1" | wc -l) > 1)); then
-            checkdir "$frootname" && mkdir "$frootname" &&
+            checkne "$frootname" && mkdir "$frootname" &&
                 tar --use-compress-program=lz4 -xf "$1" -C "$frootname" || return 1
         else
             tar --use-compress-program=lz4 -xf "$1"
@@ -93,7 +92,7 @@ ex() {
     *.lz4) lz4 -d "$1" ;;
     *.rar)
         if unrar l "$1" | grep -q '^.*/$'; then
-            checkdir "$frootname" && mkdir "$frootname" &&
+            checkne "$frootname" && mkdir "$frootname" &&
                 unrar x "$1" "$frootname" || return 1
         else
             unrar x "$1"
@@ -101,7 +100,7 @@ ex() {
         ;;
     *.tar)
         if (($(tar tf "$1" | wc -l) > 1)); then
-            checkdir "$frootname" && mkdir "$frootname" &&
+            checkne "$frootname" && mkdir "$frootname" &&
                 tar xf "$1" -C "$frootname" || return 1
         else
             tar xf "$1"
@@ -109,7 +108,7 @@ ex() {
         ;;
     *.zip)
         if zipinfo -1 "$1" | grep -q '^.*/$'; then
-            checkdir "$frootname" && mkdir "$frootname" &&
+            checkne "$frootname" && mkdir "$frootname" &&
                 unzip "$1" -d "$frootname" || return 1
         else
             unzip "$1"
@@ -117,14 +116,14 @@ ex() {
         ;;
     *.7z)
         if 7z l "$1" | grep -q '^.*/$'; then
-            checkdir "$frootname" && mkdir "$frootname" &&
+            checkne "$frootname" && mkdir "$frootname" &&
                 7z x "$1" -o"$frootname" || return 1
         else
             7z x "$1"
         fi
         ;;
-    *) echo "'$1' cannot be extracted via ex()" ;;
+    *) echo "'$1' cannot be extracted" ;;
     esac
 }
 
-ex "$1"
+main "$1"
