fix(bin): md conversion scripts cannot handle file names with spaces

diff --git a/.bin/md2html b/.bin/md2html
--- a/.bin/md2html
+++ b/.bin/md2html
@@ -10,17 +10,20 @@ md2html() {
         --css ~/.pandoc/css/paper.css \
         -t html \
         "$1" \
-        -o $(echo "$1" | sed "s/.md$/.html/")
+        -o "${1%.md}.html"
 }
 
 main() {
     for file in "$@"; do
         # Pictures in markdown cannot be fetched if
         # we are not in the same directory.
-        cd $(dirname $(fullpath "$file"))
-        md2html $(basename "$file")
-        cd -
+        cd "$(dirname "$(readlink -f "$file")")" >/dev/null 2>&1 || exit 1
+        md2html "$(basename "$file")" || {
+            echo >&2 "md2html: error: pandoc failed to convert '$file'"
+            exit 1
+        }
+        cd - >/dev/null 2>&1
     done
 }
 
-main $@
+main "$@"
diff --git a/.bin/md2html2pdf b/.bin/md2html2pdf
--- a/.bin/md2html2pdf
+++ b/.bin/md2html2pdf
@@ -4,7 +4,7 @@
 md2html2pdf() {
     pandoc \
         --katex \
-        --pdf-engine=${PDF_ENGINE} \
+        --pdf-engine="${PDF_ENGINE}" \
         -V margin-top=10 \
         -V margin-bottom=10 \
         -V margin-left=8 \
@@ -13,7 +13,7 @@ md2html2pdf() {
         -f markdown-implicit_figures \
         -t pdf \
         "$1" \
-        -o $(echo "$1" | sed "s/.md$/.pdf/")
+        -o "${1%.md}.pdf"
 }
 
 main() {
@@ -36,7 +36,7 @@ main() {
             PDF_ENGINE="pdflatex"
             ;;
         \?)
-            echo "Usage: $(basename $0) [-l|-x|-m|-h|-p] files" >&2
+            echo "Usage: $(basename "$0") [-l|-x|-m|-h|-p] files" >&2
             exit 1
             ;;
         esac
@@ -46,10 +46,13 @@ main() {
     for file in "$@"; do
         # Pictures in markdown cannot be fetched if
         # we are not in the same directory.
-        cd $(dirname $(fullpath "$file"))
-        md2html2pdf $(basename "$file")
-        cd -
+        cd "$(dirname "$(readlink -f "$file")")" >/dev/null 2>&1 || exit 1
+        md2html2pdf "$(basename "$file")" || {
+            echo >&2 "md2html2pdf: error: pandoc failed to convert '$file'"
+            exit 1
+        }
+        cd - >/dev/null 2>&1
     done
 }
 
-main $@
+main "$@"
diff --git a/.bin/md2pdf b/.bin/md2pdf
--- a/.bin/md2pdf
+++ b/.bin/md2pdf
@@ -3,8 +3,8 @@
 
 md2pdf() {
     pandoc \
-        --lua-filter ${HOME}/.pandoc/md2pdf_filter.lua \
-        --pdf-engine=${PDF_ENGINE} \
+        --lua-filter="${HOME}/.pandoc/md2pdf_filter.lua" \
+        --pdf-engine="${PDF_ENGINE}" \
         -V block-headings \
         -V colorlinks=true \
         -V CJKmainfont="Source Han Serif CN" \
@@ -12,7 +12,7 @@ md2pdf() {
         -f markdown-implicit_figures \
         -t pdf \
         "$1" \
-        -o $(echo "$1" | sed "s/.md$/.pdf/")
+        -o "${1%.md}.pdf"
 }
 
 main() {
@@ -35,7 +35,7 @@ main() {
             PDF_ENGINE="pdflatex"
             ;;
         -h | --help | -\?)
-            echo "Usage: $(basename $0) [-l|-x|-m|-h|-p] files" >&2
+            echo "Usage: $(basename "$0") [-l|-x|-m|-h|-p] files" >&2
             exit 1
             ;;
         --pdf-engine=*)
@@ -59,13 +59,13 @@ main() {
     for file in "$@"; do
         # Pictures in markdown cannot be fetched if
         # we are not in the same directory.
-        cd $(dirname $(fullpath "$file")) >/dev/null 2>&1
-        md2pdf $(basename "$file") || {
-            echo >&2 "md2pdf: error: pandoc failed to convert $file with edit code $?"
+        cd "$(dirname "$(readlink -f "$file")")" >/dev/null 2>&1 || exit 1
+        md2pdf "$(basename "$file")" || {
+            echo >&2 "md2pdf: error: pandoc failed to convert '$file' with edit code $?"
             exit 1
         }
         cd - >/dev/null 2>&1
     done
 }
 
-main $@
+main "$@"
diff --git a/.bin/md2tex b/.bin/md2tex
--- a/.bin/md2tex
+++ b/.bin/md2tex
@@ -7,17 +7,20 @@ md2tex() {
         -f markdown-implicit_figures \
         -t latex \
         "$1" \
-        -o $(echo "$1" | sed "s/.md$/.tex/")
+        -o "${1%.md}.tex"
 }
 
 main() {
     for file in "$@"; do
         # Pictures in markdown cannot be fetched if
         # we are not in the same directory.
-        cd $(dirname $(fullpath "$file"))
-        md2tex $(basename "$file")
-        cd -
+        cd "$(dirname "$(readlink -f "$file")")" >/dev/null 2>&1 || exit 1
+        md2tex "$(basename "$file")" || {
+            echo >&2 "md2tex: error: pandoc failed to convert '$file'"
+            exit 1
+        }
+        cd - >/dev/null 2>&1
     done
 }
 
-main $@
+main "$@"
