fix(bin): fix shellcheck warnings

diff --git a/.bin/rsync-fetch b/.bin/rsync-fetch
--- a/.bin/rsync-fetch
+++ b/.bin/rsync-fetch
@@ -3,8 +3,8 @@
 # Fetch files from <src> to <dest> periodically
 
 main() {
-    if ! command -v rsync >/dev/null 2>&1; then
-        echo 'rsync not found, exit'
+    if ! has rsync; then
+        echo 'rsync not found' >&2
         return 1
     fi
 
diff --git a/.bin/rsync-push b/.bin/rsync-push
--- a/.bin/rsync-push
+++ b/.bin/rsync-push
@@ -9,9 +9,8 @@ push() {
 }
 
 main() {
-    if ! command -v rsync >/dev/null 2>&1 ||
-        ! command -v inotifywait >/dev/null 2>&1; then
-        echo 'rsync or inotifywait not found, exit'
+    if ! has rsync || ! has inotifywait; then
+        echo 'rsync or inotifywait not found'
         return 1
     fi
 
