feat(bin): echo reply from http://ipinfo.io/loc on fail

diff --git a/.bin/whereami b/.bin/whereami
--- a/.bin/whereami
+++ b/.bin/whereami
@@ -15,7 +15,7 @@ else
 fi
 
 if [ -z "$coords" ] || ! (echo "$coords" | grep -Eq '^([+-]?[0-9]+\.[0-9]+,?){2}$'); then
-    echo "Failed to get location from $LOC_URL" >&2
+    echo "Failed to get location from $LOC_URL: $coords" >&2
     exit 1
 fi
 
