Add .stylua.toml and .editorconfig and format code under .scripts/

diff --git a/.scripts/md2pdf b/.scripts/md2pdf
--- a/.scripts/md2pdf
+++ b/.scripts/md2pdf
@@ -3,54 +3,55 @@
 
 md2pdf() {
     pandoc \
-    --lua-filter ${HOME}/.scripts/pandoc_filters/md2pdf_filter.lua \
-    --pdf-engine=${PDF_ENGINE} \
-    -V block-headings \
-    -V colorlinks=true \
-    -V CJKmainfont="Source Han Serif CN" \
-    -V geometry:margin=1in \
-    -f markdown-implicit_figures \
-    -t pdf \
-    "$1" \
-    -o $(echo "$1" | sed "s/.md$/.pdf/")
+        --lua-filter ${HOME}/.scripts/pandoc_filters/md2pdf_filter.lua \
+        --pdf-engine=${PDF_ENGINE} \
+        -V block-headings \
+        -V colorlinks=true \
+        -V CJKmainfont="Source Han Serif CN" \
+        -V geometry:margin=1in \
+        -f markdown-implicit_figures \
+        -t pdf \
+        "$1" \
+        -o $(echo "$1" | sed "s/.md$/.pdf/")
 }
 
 main() {
     PDF_ENGINE="pdflatex"
     while :; do
         case $1 in
-            -l|--lualatex)
-                PDF_ENGINE="lualatex"
-                ;;
-            -x|--xelatex)
-                PDF_ENGINE="xelatex"
-                ;;
-            -m|--latexmk)
-                PDF_ENGINE="latexmk"
-                ;;
-            -w|--wkhtmltopdf)
-                PDF_ENGINE="wkhtmltopdf"
-                ;;
-            -p|--pdflatex)
-                PDF_ENGINE="pdflatex"
-                ;;
-            -h|--help|-\?)
-                echo "Usage: md2pdf [-l|-x|-m|-h|-p] files" >&2
-                exit 1
-                ;;
-            --pdf-engine=*)
-                PDF_ENGINE="${1#*=}"
-                ;;
-            --pdf_engine)
-                PDF_ENGINE="$2"
-                shift
-                ;;
-            --)
-                shift
-                break
-                ;;
-            *)
-                break
+        -l | --lualatex)
+            PDF_ENGINE="lualatex"
+            ;;
+        -x | --xelatex)
+            PDF_ENGINE="xelatex"
+            ;;
+        -m | --latexmk)
+            PDF_ENGINE="latexmk"
+            ;;
+        -w | --wkhtmltopdf)
+            PDF_ENGINE="wkhtmltopdf"
+            ;;
+        -p | --pdflatex)
+            PDF_ENGINE="pdflatex"
+            ;;
+        -h | --help | -\?)
+            echo "Usage: md2pdf [-l|-x|-m|-h|-p] files" >&2
+            exit 1
+            ;;
+        --pdf-engine=*)
+            PDF_ENGINE="${1#*=}"
+            ;;
+        --pdf_engine)
+            PDF_ENGINE="$2"
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        *)
+            break
+            ;;
         esac
         shift
     done
@@ -60,7 +61,7 @@ main() {
         # we are not in the same directory.
         cd $(dirname $(full_path "$file")) >/dev/null 2>&1
         md2pdf $(basename "$file") || {
-            >&2 echo "md2pdf: error: pandoc failed to convert $file with edit code $?"
+            echo >&2 "md2pdf: error: pandoc failed to convert $file with edit code $?"
             exit 1
         }
         cd - >/dev/null 2>&1
diff --git a/.scripts/pacman-comment b/.scripts/pacman-comment
--- a/.scripts/pacman-comment
+++ b/.scripts/pacman-comment
@@ -3,7 +3,7 @@
 
 prepare() {
     if [[ "$EUID" -ne 0 ]]; then
-        >&2 echo "error: you cannot perform this operation unless you are root."
+        echo >&2 "error: you cannot perform this operation unless you are root."
         exit 1
     fi
     PKGS_LOGPATH="/var/log/"
@@ -19,7 +19,7 @@ add_comments() {
     if [[ -f "$VEDITOR" ]]; then
         EXCMD="set expandtab softtabstop=4 tabstop=4 shiftwidth=4"
         # Let vi search for the newly installed packages, redirect I/O to terminal
-        $VEDITOR -c "$EXCMD" "$PKGS_LOGFILE" < /dev/tty > /dev/tty
+        $VEDITOR -c "$EXCMD" "$PKGS_LOGFILE" </dev/tty >/dev/tty
     else
         echo -e "\033[1;33mwarning:\033[0m vi not available -- add comments to ${PKGS_LOGFILE} manually"
     fi
diff --git a/.scripts/run b/.scripts/run
--- a/.scripts/run
+++ b/.scripts/run
@@ -3,10 +3,12 @@
 
 build() {
     case "$1" in
-        *.c)
-            gcc "$1" -o "$2";;
-        *.cpp)
-            g++ "$1" -o "$2";;
+    *.c)
+        gcc "$1" -o "$2"
+        ;;
+    *.cpp)
+        g++ "$1" -o "$2"
+        ;;
     esac
 }
 
@@ -18,12 +20,12 @@ main() {
     FILE=$(full_path "$1")
     RUN_FILE=$(echo "$FILE" | sed -E 's/\.(c|cpp)$/.run/')
     if [[ "$FILE" == "$RUN_FILE" ]]; then
-        >&2 echo "run: error: file name cannot be the same as the run file name"
+        echo >&2 "run: error: file name cannot be the same as the run file name"
         exit 1
     fi
     build "$FILE" "$RUN_FILE"
     if [[ ! -f "$RUN_FILE" ]]; then
-        >&2 echo "run: error: cannot remove run file because it does not exist"
+        echo >&2 "run: error: cannot remove run file because it does not exist"
         exit 1
     fi
     exec "$RUN_FILE"
