Echo script error messages to stderr

diff --git a/.scripts/pacman-comment b/.scripts/pacman-comment
--- a/.scripts/pacman-comment
+++ b/.scripts/pacman-comment
@@ -3,7 +3,7 @@
 
 prepare() {
     if [[ "$EUID" -ne 0 ]]; then
-        echo "error: you cannot perform this operation unless you are root."
+        >&2 echo "error: you cannot perform this operation unless you are root."
         exit 1
     fi
     PKGS_LOGPATH="/var/log/"
diff --git a/.scripts/run b/.scripts/run
--- a/.scripts/run
+++ b/.scripts/run
@@ -18,12 +18,12 @@ main() {
     FILE=$(full_path "$1")
     RUN_FILE=$(echo "$FILE" | sed -E 's/\.(c|cpp)$/.run/')
     if [[ "$FILE" == "$RUN_FILE" ]]; then
-        echo "run: error: file name cannot be the same as the run file name"
+        >&2 echo "run: error: file name cannot be the same as the run file name"
         exit 1
     fi
     build "$FILE" "$RUN_FILE"
     if [[ ! -f "$RUN_FILE" ]]; then
-        echo "run: error: cannot remove run file because it does not exist"
+        >&2 echo "run: error: cannot remove run file because it does not exist"
         exit 1
     fi
     exec "$RUN_FILE"
